### ISSUE TITLE
alt+| doesn't work as described in README

### ISSUE THREAD

**Issue by rmchale** [markbirbeck/sublime-text-shell-command#63]
I love the idea of highlighting text and having it run in shell.  I couldn't get `alt+|` to work any differently than `alt+!`.   I am running Sierra and ST3 Build 3126.  They both just open the shell-command bar.

**Comment by dbarros** [comment]
I'm seeing the same thing. Is there a fix for this?

**Comment by markbirbeck** [comment]
So the first thing to say on this is that the 'problem' is actually to do with poor documentation! (See #5 for a bit more on this.)

The `alt+|` command doesn't execute the selected text, but rather uses the selected text as `stdin` for whatever command you run. So if you wanted to sort some lines of a file you could select them, press `alt+|` and then type `sort`; the sorted output will go to a new window.

(If you don't select any lines the whole file will get sorted, and if you use `ctrl+alt+|` the output will be inserted into the current file instead of opening a new window.)

But what is lacking is a key combination that uses the text in a file as the command itself.

However, you can create your own entry to do what you want. All you need to do is create an entry with a blank `command` parameter, and then obtain the `arg` value from the selected region (see [Use cursor selection for input](https://github.com/markbirbeck/sublime-text-shell-command#use-cursor-selection-for-input). Something like this:

```json
[
  {
    "keys": ["blah+de+blah"],
    "command": "shell_command",
    "args": {
      "command": "",
      "region": "arg"
    }
  }
]
```

Now if you had a file like this:

```shell
ls -al
date
```

you could:

* place the cursor on the beginning of the first line and invoke your key combination to perform `ls -al`;
* place the cursor on the beginning of the second line and invoke your key combination to perform `date`;
* select all of the text and invoke your key combination to perform `ls -al` and then `date`.

**Comment by markbirbeck** [comment]
Closing this since it's really about documentation. However, opened #66 to track adding a key binding.
